In [1]:
import pandas as pd
import numpy as np

In [53]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [54]:
data = pd.read_csv('modified.csv')

In [55]:
data

Unnamed: 0   age     bp     sg   al   su     rbc        pc         pcc  \
0             2  62.0   80.0  1.010  2.0  3.0  normal    normal  notpresent   
1             3  48.0   70.0  1.005  4.0  0.0  normal  abnormal     present   
2             4  51.0   80.0  1.010  2.0  0.0  normal    normal  notpresent   
3             7  24.0    NaN  1.015  2.0  4.0  normal  abnormal  notpresent   
4             8  52.0  100.0  1.015  3.0  0.0  normal  abnormal     present   
..          ...   ...    ...    ...  ...  ...     ...       ...         ...   
228         395  55.0   80.0  1.020  0.0  0.0  normal    normal  notpresent   
229         396  42.0   70.0  1.025  0.0  0.0  normal    normal  notpresent   
230         397  12.0   80.0  1.020  0.0  0.0  normal    normal  notpresent   
231         398  17.0   60.0  1.025  0.0  0.0  normal    normal  notpresent   
232         399  58.0   80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv      wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   31  7500.0  NaN   no  yes   no  poor   no  yes   
1    notpresent  ...   32  6700.0  3.9  yes   no   no  poor  yes  yes   
2    notpresent  ...   35  7300.0  4.6   no   no   no  good   no   no   
3    notpresent  ...   44  6900.0  5.0   no  yes   no  good  yes   no   
4    notpresent  ...   33  9600.0  4.0  yes  yes   no  good   no  yes   
..          ...  ...  ...     ...  ...  ...  ...  ...   ...  ...  ...   
228  notpresent  ...   47  6700.0  4.9   no   no   no  good   no   no   
229  notpresent  ...   54  7800.0  6.2   no   no   no  good   no   no   
230  notpresent  ...   49  6600.0  5.4   no   no   no  good   no   no   
231  notpresent  ...   51  7200.0  5.9   no   no   no  good   no   no   
232  notpresent  ...   53  6800.0  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
228         notckd  
229         notckd  
230         notckd  
231         notckd  
232         notckd  

[233 rows x 26 columns]

In [56]:
data[data.isin(["?", "\t?"]).any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hemo, pcv, wc, rc, htn, dm, cad, appet, pe, ane, classification]
Index: []

[0 rows x 26 columns]

In [57]:
data.sample(10)

Unnamed: 0   age     bp     sg   al   su       rbc        pc         pcc  \
53          146  53.0  100.0  1.010  1.0  3.0  abnormal    normal  notpresent   
122         275  52.0   80.0  1.020  0.0  0.0    normal    normal  notpresent   
188         354  32.0   60.0  1.025  0.0  0.0    normal    normal  notpresent   
172         336  25.0   60.0  1.020  0.0  0.0    normal    normal  notpresent   
24           61  67.0   80.0  1.010  1.0  3.0    normal  abnormal  notpresent   
46          130  50.0   90.0  1.010  2.0  0.0    normal  abnormal     present   
144         304  33.0   80.0  1.025  0.0  0.0    normal    normal  notpresent   
183         347  43.0   60.0  1.025  0.0  0.0    normal    normal  notpresent   
104         256  60.0   80.0  1.025  0.0  0.0    normal    normal  notpresent   
206         372  72.0   60.0  1.020  0.0  0.0    normal    normal  notpresent   

             ba  ...  pcv       wc   rc  htn   dm  cad appet   pe  ane  \
53   notpresent  ...  NaN      NaN  NaN   no  yes   no  good   no   no   
122  notpresent  ...   43   4700.0  4.6   no   no   no  good   no   no   
188  notpresent  ...   41   6800.0  5.1   no   no   no  good   no   no   
172  notpresent  ...   40   9200.0  5.2   no   no   no  good   no   no   
24   notpresent  ...  NaN      NaN  NaN   no   no   no  good  yes   no   
46      present  ...   22  16300.0  2.7   no   no   no  poor  yes  yes   
144  notpresent  ...   45   6200.0  4.5   no   no   no  good   no   no   
183  notpresent  ...   43   7200.0  5.5   no   no   no  good   no   no   
104  notpresent  ...   41  10700.0  5.1   no   no   no  good   no   no   
206  notpresent  ...   52  10500.0  5.5   no   no   no  good   no   no   

    classification  
53             ckd  
122         notckd  
188         notckd  
172         notckd  
24             ckd  
46             ckd  
144         notckd  
183         notckd  
104         notckd  
206         notckd  

[10 rows x 26 columns]

In [58]:
data.isnull().sum()

Unnamed: 0         0
age                4
bp                 4
sg                 1
al                 1
su                 1
rbc                0
pc                 0
pcc                0
ba                 0
bgr               21
bu                10
sc                 9
sod               31
pot               31
hemo              19
pcv               20
wc                36
rc                47
htn                0
dm                 0
cad                0
appet              0
pe                 0
ane                0
classification     0
dtype: int64

In [129]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train ,y_test = train_test_split(data.drop('classification' , axis = 1) , data['classification'] , test_size = 0.2)

In [130]:
y_test

100    notckd
117    notckd
113    notckd
119    notckd
220    notckd
65        ckd
214    notckd
132    notckd
27        ckd
4         ckd
215    notckd
21        ckd
204    notckd
172    notckd
50        ckd
121    notckd
228    notckd
51        ckd
205    notckd
80        ckd
206    notckd
76        ckd
226    notckd
13        ckd
90        ckd
223    notckd
8         ckd
130    notckd
115    notckd
70        ckd
178    notckd
31        ckd
181    notckd
164    notckd
133    notckd
88        ckd
42        ckd
23        ckd
199    notckd
211    notckd
203    notckd
136    notckd
140    notckd
84        ckd
60        ckd
95        ckd
3         ckd
Name: classification, dtype: object

In [101]:
import numpy as np

# Clean numeric columns
cols1 = ['age' , 'bp' , 'sg' , 'al' , 'su' , 'bgr' , 'bu' , 'sc' , 
         'sod' , 'pot' , 'hemo' , 'pcv' , 'wc' , 'rc']
# Clean only cols1
for col in cols1:
    X_train[col] = (
        X_train[col]
        .astype(str)                                # ensure string
        .str.replace(r'[\t?]', '', regex=True)      # remove tabs and '?'
        .str.strip()                                # strip spaces
    )
    X_train[col] = pd.to_numeric(X_train[col], errors='coerce')  # convert → numeric

# Apply imputer only on cols1
si = SimpleImputer(strategy="mean")
X_train[cols1] = si.fit_transform(X_train[cols1])

In [102]:
X_train_clean

array([[5.10000000e+01, 1.00000000e+02, 1.01500000e+00, ...,
        4.04444444e+01, 8.20193548e+03, 4.85238095e+00],
       [6.00000000e+01, 1.00000000e+02, 1.02000000e+00, ...,
        2.90000000e+01, 8.20193548e+03, 4.85238095e+00],
       [1.20000000e+01, 8.00000000e+01, 1.02000000e+00, ...,
        4.90000000e+01, 6.60000000e+03, 5.40000000e+00],
       ...,
       [4.90000000e+01, 8.00000000e+01, 1.02000000e+00, ...,
        4.10000000e+01, 5.60000000e+03, 4.90000000e+00],
       [6.00000000e+01, 6.00000000e+01, 1.02000000e+00, ...,
        4.80000000e+01, 1.07000000e+04, 5.60000000e+00],
       [5.30000000e+01, 1.00000000e+02, 1.01000000e+00, ...,
        4.04444444e+01, 8.20193548e+03, 4.85238095e+00]])

In [103]:
X_train[X_train.isin(["\t?"]).any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hemo, pcv, wc, rc, htn, dm, cad, appet, pe, ane]
Index: []

[0 rows x 25 columns]

In [104]:
X_train_clean_int = X_train_clean.astype(int)

In [105]:
X_train_clean_int = pd.DataFrame(X_train_clean_int, columns=['age' , 'bp' , 'sg' , 'al' , 'su' , 
                                                 'bgr' , 'bu' , 'sc' , 'sod' , 'pot' , 
                                                 'hemo' , 'pcv' , 'wc' , 'rc'])

In [106]:
X_train_clean_int

age   bp  sg  al  su  bgr   bu  sc  sod  pot  hemo  pcv     wc  rc
0     51  100   1   2   0   93   20   1  146    4    13   40   8201   4
1     60  100   1   2   0  140   55   2  138    4    10   29   8201   4
2     12   80   1   0   0  100   26   0  137    4    15   49   6600   5
3     64  100   1   4   2  163   54   7  140    4     7   26   7500   3
4     68   70   1   1   0  139   28   1  138    4    12   38   8201   4
..   ...  ...  ..  ..  ..  ...  ...  ..  ...  ...   ...  ...    ...  ..
181   73   80   1   2   0  253  142   4  138    5    10   33   7200   4
182   52   80   1   0   0  125   22   1  139    4    16   43   4700   4
183   49   80   1   0   0  122   32   1  139    3    17   41   5600   4
184   60   60   1   0   0  134   45   0  139    4    14   48  10700   5
185   53  100   1   1   3  213   23   1  139    4    13   40   8201   4

[186 rows x 14 columns]

In [107]:
#Applying Minmax Scaling
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
X_train_scaled = scale.fit_transform(X_train_clean_int)

In [108]:
X_train_scaled

array([[0.60493827, 1.        , 0.        , ..., 0.68888889, 0.35934132,
        0.5       ],
       [0.71604938, 1.        , 0.        , ..., 0.44444444, 0.35934132,
        0.5       ],
       [0.12345679, 0.6       , 0.        , ..., 0.88888889, 0.26347305,
        0.75      ],
       ...,
       [0.58024691, 0.6       , 0.        , ..., 0.71111111, 0.20359281,
        0.5       ],
       [0.71604938, 0.2       , 0.        , ..., 0.86666667, 0.50898204,
        0.75      ],
       [0.62962963, 1.        , 0.        , ..., 0.68888889, 0.35934132,
        0.5       ]])

In [116]:
# Define categorical columns and mapping dictionary
categorical_columns = ['htn' , 'dm' , 'cad' , 'pe' , 'ane' , 'rbc' , 'pc' , 'pcc' , 'ba' ]
cols = ['htn', 'dm' , 'cad' , 'pe' , 'ane']
cats = [['no' , 'yes'] , ['no' , 'yes'] , ['no' , 'yes'] , ['no' , 'yes'] , ['no' , 'yes']]

In [124]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [125]:
y_train = le.transform(y_train)

In [131]:
y_test = le.transform(y_test)

In [132]:
y_test

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0])